---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_management_node.html 
summary: 在升級版的過程中、您需要升級管理節點。NetApp HCI 
keywords: netapp, hci, on premise, cluster, management node, mNode, upgrade, 10, 11.0, 11.1, 11.3, 11.5, 11.7, 12.0, 12.2, 12.3, 12.3.1, 12.3.2, 12.3.x, 12.5, 12.7, 12.8 
---
= 升級管理節點
:allow-uri-read: 


[role="lead"]
您可以將管理節點從12.3.x版或更新版本升級至管理節點12.5或更新版本。

不再需要升級管理節點作業系統、即可升級儲存叢集上的Element軟體。您只需將管理服務升級至最新版本、即可使用NetApp混合雲控制系統執行元件升級。如果您基於其他理由（例如安全性補救）而想要升級管理節點作業系統、請依照您案例的管理節點升級程序進行。


NOTE: 如果您需要有關升級管理節點12．2或更早版本的資訊、請參閱 https://docs.netapp.com/us-en/hci19/docs/task_hcc_upgrade_management_node.html["更新說明文件NetApp HCI"^]。



== 步驟 1 ：在管理節點上升級 VM 硬體版本

如果您要將現有管理節點就地升級到 Element 12.8 或更高版本，則在升級之前，必須確保管理節點上的 VM 硬體版本與您的環境相容於 ESXi 6.7（VM 硬體版本 14）或更高版本。


NOTE: 您也可以依照下列步驟，在見證節點上升級 VM 硬體版本。

.步驟
. 以vCenter管理員身分登入vSphere Web Client。
. 從 vSphere Client 功能表中，選取 * VM and Templates] 。
. 在虛擬機器（ VM ）上按一下滑鼠右鍵，然後選取 * 電源 * > * 關閉來賓作業系統 * 。
+
等到虛擬機器關機。

. 在 VM 上按一下滑鼠右鍵，然後選取 * 相容性 * > * 升級 VM 相容性 * 。
. 選擇*是*。
. 根據 vSphere 環境的版本，選取 ESXi 6.7 或更新版本。
. 選擇*確定*。
. 升級完成後，在虛擬機器上按一下滑鼠右鍵，然後選取 * Power* > * Power On* 。
. 選取 * vSphere 用戶端重新整理 * ，並確認 VM 相容性為所需版本。




== 步驟 2 ：將管理節點升級至元件 12.5 或更新版本

請選擇下列其中一個升級選項：

* <<將管理節點從12.3.x版或更新版本升級至12.5版或更新版本>>
* <<使用管理節點REST API重新設定驗證>>
+
如果您已*連續*更新管理服務版本（1）、以及（2）您的元素儲存版本、而且您想*保留*現有的管理節點、請選擇此選項：




NOTE: 如果您未依序更新管理服務、接著更新元素儲存設備、則無法使用此程序重新設定重新驗證。請改為執行適當的升級程序。



=== 將管理節點從12.3.x版或更新版本升級至12.5版或更新版本

您可以在不需要佈建新管理節點虛擬機器的情況下、將管理節點從12.3.x或更新版本就地升級至12.5或更新版本。


NOTE: Element 12.5或更新版本的管理節點為選用升級。現有部署不需要此功能。

.開始之前
* 管理節點VM的RAM為24GB。
* 您要升級的管理節點為12版、使用的是IPv6網路。管理節點版本12.5或更新版本不支援IPv6。
+

TIP: 若要檢查管理節點的版本、請登入管理節點、然後在登入橫幅中檢視元素版本編號。

* 您已使用NetApp混合雲控制將管理服務套裝組合更新為最新版本。您可以從下列IP存取NetApp混合雲控制：「\https://<ManagementNodeIP>`」
* 如果您要將管理節點更新至版本12．5或更新版本、則需要使用管理服務2．21．61或更新版本才能繼續。
* 您已依照的指示設定其他網路介面卡（如有需要） link:task_mnode_install_add_storage_NIC.html["設定額外的儲存NIC"]。
+

NOTE: 如果eth0無法路由至SVIP、則持續磁碟區可能需要額外的網路介面卡。在iSCSI儲存網路上設定新的網路介面卡、以允許設定持續磁碟區。

* 儲存節點執行元件12.3.x或更新版本。


.步驟
. 使用SSH或主控台存取權登入管理節點虛擬機器。
. 下載 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["管理節點ISO"^] 適用於從NetApp Support網站到管理節點虛擬機器的Element軟體。
+

NOTE: ISO的名稱類似於「Poolidfire - fdva-<Element版本>-增補 軟體X-XX.x.XXXX.ISO」

. 請在下載的檔案上執行md5sum、檢查下載內容的完整性、並將輸出與NetApp Support網站上的Element軟體進行比較、如下列範例所示：
+
「Udo md5sum -b <指向iso>/sidfire-fdva-<元件版本>-patchX-XX.x.XXXX.iso'

. 掛載管理節點ISO映像、並使用下列命令將內容複製到檔案系統：
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount <solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso> /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. 切換到主目錄、然後從「/mnt」卸載ISO檔案：
+
[listing]
----
sudo umount /mnt
----
. 刪除ISO以節省管理節點上的空間：
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. 在您要升級的管理節點上、執行下列命令來升級管理節點OS版本。指令碼會在升級後保留所有必要的組態檔、例如Active IQ 收集器和Proxy設定。
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1
----
+
升級程序完成後、管理節點會以新的作業系統重新開機。

+

NOTE: 執行本步驟所述的Sudo命令後、SSH工作階段便會終止。需要主控台存取才能繼續監控。如果您在執行升級時無法存取主控台、請重試SSH登入、並在15至30分鐘後驗證連線能力。登入之後、您可以在SSH橫幅中確認新的作業系統版本、表示升級成功。

. 在管理節點上、執行「部署節點」指令碼、以保留先前的管理服務組態設定：
+

NOTE: 指令碼會保留先前的管理服務組態、包括Active IQ 來自於資料收集器服務、控制器（vCenters）或Proxy的組態、視您的設定而定。

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>
----



IMPORTANT: 如果您先前已停用管理節點上的SSH功能、則需要 link:task_mnode_ssh_management.html["再次停用SSH"] 在恢復的管理節點上。提供SSH功能 link:task_mnode_enable_remote_support_connections.html["NetApp支援遠端支援通道（RST）工作階段存取"] 預設會在管理節點上啟用。



=== 使用管理節點REST API重新設定驗證

如果您已依序升級（1）管理服務和（2）元素儲存設備、則可以保留現有的管理節點。如果您已依照不同的升級順序執行、請參閱就地管理節點升級程序。

.開始之前
* 您已將管理服務更新為2.20.69或更新版本。
* 您的儲存叢集正在執行Element 123或更新版本。
* 您已依序更新管理服務、然後升級您的Element儲存設備。除非您依照所述順序完成升級、否則無法使用此程序重新設定驗證。


.步驟
. 在管理節點上開啟管理節點REST API UI：
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. 選擇*授權*並完成下列項目：
+
.. 輸入叢集使用者名稱和密碼。
.. 如果尚未填入值、請將用戶端ID輸入為「mnode-client」。
.. 選取*授權*以開始工作階段。


. 從REST API UI中、選取* POST /services / reconfigure驗證*。
. 選擇*試用*。
. 對於* load_ims*參數、請選取「true」。
. 選擇*執行*。
+
回應本文表示重新設定成功。





== 如需詳細資訊、請參閱

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]
